/**
 * F4 — RefusalEnvelope spec (M8 Phase D, D18).
 *
 * Type spec + helpers + locked envelope content for the three
 * Koast-as-publisher refusal categories. Voice doctrine §2.3.4 is the
 * source of truth for refusal language; the constants below are the
 * production copy reviewed at F4 sign-off.
 *
 * M8 generation scope:
 *   - hard_refusal only, generated by P4 at propose_guest_message for
 *     the three publisher categories.
 *   - soft_refusal + host_input_needed: type ships for forward-compat;
 *     generation ships when M9 broadens output schema enforcement at
 *     all four LLM call sites.
 *
 * Voice doctrine bindings:
 *   - §2.3.4 — three publisher refusal categories (the canonical
 *     sentence used verbatim in Category 3 below).
 *   - §4.1 — three refusal flavors with distinct semantics.
 *   - §4.2 — hard refusal pattern shape (direct + specific reason +
 *     concrete alternative path).
 *   - §4.3 — banned anti-patterns (apology theater, corporate framing,
 *     model-trained safety voice, sycophantic preface, redirect-speak).
 *   - §3.6 — confidence calibration applies even when news is bad.
 */

/**
 * Three refusal flavors locked in voice doctrine §4. All three ship in
 * M8 type spec + render path; only hard_refusal is auto-generated in
 * M8 (P4 at propose_guest_message).
 *
 *   - hard_refusal: door closed categorically. Out-of-scope per §2.3.4.
 *     override_available is always false.
 *   - soft_refusal: advisory pushback (§4.2). Door open via host
 *     override. M8 has no auto-generation surface; M9 candidate.
 *   - host_input_needed: door open via missing info (§4.4). Different
 *     shape from refusal — opens a path rather than closing one. Today
 *     handled inline by tool error responses; formal envelope generation
 *     is M9.
 */
export type RefusalKind = "hard_refusal" | "soft_refusal" | "host_input_needed";

export type RefusalEnvelope = {
  kind: RefusalKind;
  /** 1-2 sentences, specific. §3.6 confidence calibration applies. */
  reason: string;
  /** Concrete next step the host can take. Hard/soft refusals only. */
  alternative_path?: string;
  /** Soft refusal only. Hard is always false; host_input_needed N/A. */
  override_available?: boolean;
  /** host_input_needed only. */
  missing_inputs?: string[];
  /** host_input_needed only. */
  suggested_inputs?: string[];
};

// ----------------------------------------------------------------------
// Type guard + validation
// ----------------------------------------------------------------------

/**
 * Runtime guard for cross-boundary deserialization (e.g., reading an
 * envelope off a turn payload). Validates required fields + kind enum;
 * does not enforce per-kind field semantics (that's caller discipline).
 */
export function isRefusalEnvelope(value: unknown): value is RefusalEnvelope {
  if (!value || typeof value !== "object") return false;
  const v = value as Record<string, unknown>;
  if (
    v.kind !== "hard_refusal" &&
    v.kind !== "soft_refusal" &&
    v.kind !== "host_input_needed"
  ) {
    return false;
  }
  if (typeof v.reason !== "string" || v.reason.length === 0) return false;
  return true;
}

// ----------------------------------------------------------------------
// Locked envelope content for P4 (M8 hard_refusal generation)
// ----------------------------------------------------------------------

/**
 * P4 publisher-category classifier resolves to one of these three
 * keys; envelope content adapts the bracketed professional term in
 * Category 3 via `professionalTerm` substitution.
 */
export type PublisherCategory = "legal" | "regulatory" | "licensed_professional";

/**
 * Build a hard_refusal envelope for a Category 3 (licensed-professional)
 * refusal with the host-named professional substituted. If the
 * classifier can't disambiguate, default to "advisor" per F4 sign-off.
 */
export function buildLicensedProfessionalRefusal(
  professionalTerm: "lawyer" | "CPA" | "advisor" = "advisor",
): RefusalEnvelope {
  return {
    kind: "hard_refusal",
    reason: `This is the kind of correspondence that should come directly from you to your ${professionalTerm}. Substantive communication with licensed professionals routes around me.`,
    alternative_path:
      "I can help you think it through or pull data you need. Want me to summarize what's relevant?",
    override_available: false,
  };
}

export const LEGAL_CORRESPONDENCE_REFUSAL: RefusalEnvelope = {
  kind: "hard_refusal",
  reason:
    "This looks like legal correspondence. It should come directly from you, not from a draft I generated.",
  alternative_path:
    "I can help you think it through or pull the booking facts you'd need to draft it yourself. Want me to summarize what's relevant?",
  override_available: false,
};

export const REGULATORY_SUBMISSION_REFUSAL: RefusalEnvelope = {
  kind: "hard_refusal",
  reason:
    "This looks like a regulatory submission. It should come from you and be signed by you, not authored by a draft I generated.",
  alternative_path:
    "I can compile the totals or pull the booking records the filing needs. Want me to pull what's relevant?",
  override_available: false,
};

/**
 * Resolve a PublisherCategory key to its locked envelope content.
 * Category 3 defaults to "advisor"; callers with classifier-derived
 * specificity (host named "my CPA" / "my lawyer") should call
 * buildLicensedProfessionalRefusal directly.
 */
export function envelopeForPublisherCategory(
  category: PublisherCategory,
): RefusalEnvelope {
  switch (category) {
    case "legal":
      return LEGAL_CORRESPONDENCE_REFUSAL;
    case "regulatory":
      return REGULATORY_SUBMISSION_REFUSAL;
    case "licensed_professional":
      return buildLicensedProfessionalRefusal();
  }
}
