export const PLANS = {
  free: {
    name: "Free",
    maxProperties: 1,
    calendarSync: "ical",
    pricingSuggestions: true,
    pricingAutoPush: false,
    aiMessagesPerMonth: 10,
    marketData: true,
    reviewAutomation: false,
    turnoverOps: "manual",
    directBookingWebsite: false,
    guestCrm: false,
    ownerReports: false,
    price: 0,
  },
  pro: {
    name: "Pro",
    maxProperties: 15,
    calendarSync: "channex",
    pricingSuggestions: true,
    pricingAutoPush: true,
    aiMessagesPerMonth: -1,
    marketData: true,
    reviewAutomation: true,
    turnoverOps: "auto",
    directBookingWebsite: false,
    guestCrm: false,
    ownerReports: false,
    price: 79,
  },
  business: {
    name: "Business",
    maxProperties: -1,
    calendarSync: "channex",
    pricingSuggestions: true,
    pricingAutoPush: true,
    aiMessagesPerMonth: -1,
    marketData: true,
    reviewAutomation: true,
    turnoverOps: "auto",
    directBookingWebsite: true,
    guestCrm: true,
    ownerReports: true,
    price: 149,
  },
} as const;

export type PlanName = keyof typeof PLANS;
export type Plan = (typeof PLANS)[PlanName];
