-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  DESTRUCTIVE — CONFIRMED by Cesar 2026-06-12 (P6-continuation). Applied    ║
-- ║  staging→verify→prod→verify→record per the migration discipline.          ║
-- ╚══════════════════════════════════════════════════════════════════════════╝
--
-- P6.2 — drop the vestigial pg_net turnover trigger. Verified against prod
-- 2026-06-12: the trigger `bookings_fire_turnover_task` (function
-- `fire_turnover_task_create`) was installed INERT in P1 (migration
-- 20260426060000_bookings_turnover_trigger_inert.sql) as stage 2a of a two-stage
-- pg_net cutover whose stage 2b never shipped — the app + booking_sync.py create
-- cleaning_tasks directly instead. The trigger fires on EVERY booking insert/update
-- today, returns early (no side effect), and is pure overhead + a confusing
-- supply-chain artifact (pg_net http_post path that is never used).
--
-- Safety: dropping the trigger CANNOT lose turnover-task creation — that path is
-- the app/worker, not this trigger (which has been inert since install). Rollback
-- is trivial (re-run 20260426060000).
--
-- Verify after apply:
--   SELECT 1 FROM pg_trigger WHERE tgname='bookings_fire_turnover_task';  -- 0 rows
--   SELECT 1 FROM pg_proc    WHERE proname='fire_turnover_task_create';   -- 0 rows
--   -- bookings still ingest (the trigger was inert, so no behavior change):
--   SELECT count(*) FROM bookings WHERE created_at > now() - interval '1 hour';

DROP TRIGGER IF EXISTS bookings_fire_turnover_task ON bookings;
DROP FUNCTION IF EXISTS fire_turnover_task_create();

-- ── pg_net EXTENSION: DELIBERATELY LEFT INSTALLED (consumer-check result) ────
-- Cesar's confirm was conditional: drop the extension too ONLY IF a both-DB
-- consumer scan finds zero other references to net.http_* besides the trigger
-- above; otherwise leave it and document why. The scan (2026-06-12, staging +
-- prod, identical results) found ONE other reference:
--
--   extensions.grant_pg_net_access()  — a Supabase PLATFORM-managed event-trigger
--   function (fires on CREATE EXTENSION pg_net to provision supabase_functions_admin
--   and grant USAGE on the net schema). It is platform plumbing, not a Koast consumer.
--
-- Because pg_net is a Supabase baseline extension entangled with that managed
-- event trigger, `DROP EXTENSION pg_net CASCADE` would drop/break Supabase's own
-- plumbing — not safe on a managed project. The supply-chain concern was the
-- TRIGGER invoking net.http_post (removed above); the unused extension sitting
-- idle is harmless. Decision: KEEP pg_net. (pg_cron is not installed in either
-- DB, so there are no scheduled net.http_* jobs either.)
--
-- DROP EXTENSION pg_net — intentionally NOT executed.
